name: Flask CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 클론
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker 로그인
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Docker 이미지 빌드 및 푸시
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/errorcode-ai-server:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/errorcode-ai-server:latest

    # 4. 원격 서버에서 배포 스크립트 실행 (CD)
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # EC2 인스턴스 퍼블릭 DNS
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }} # pem 키
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/errorcode-ai-server:latest
          sudo docker stop errorcode-ai-server || true
          sudo docker rm errorcode-ai-server || true
          sudo docker run -d -p 5000:5000 --name errorcode-ai-server ${{ secrets.DOCKER_USERNAME }}/errorcode-ai-server:latest
          sudo docker rm $(sudo docker ps --filter 'status=exited' -a -q)
          sudo docker image prune -a -f
